# Generated by Django 5.0.6 on 2024-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlr')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('body', models.TextField(verbose_name='Body')),
                ('data', models.DateTimeField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
